application.data-dir: D:\inventory-api
server:
  port: 8085
spring.mail:
  protocol: smtp
  host: smtp.gmail.com
  port: 587
  username: nielnaga66@gmail.com
  password: edgpiilqyrnmthez
  properties.mail.smtp:
    auth: true
    starttls.enable: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/credit_scoring?serverTimezone=UTC
    username: root
    password: admin
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: i18n/messages
#  servlet:
#    multipart:
#      max-file-size: 1MB
#      max-request-size: 1MB
#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html